
spring:
  application:
    name: listit
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/listit
    username: listit
    password: qwe123
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
 # security:
 #   oauth2:
 #     client:
 #       registration:
 #         github:
 #           client-id: https://github.com/apps/listit-uem-cs
 #            client-secret: 48cd361bf16f6c07a17f0dd4b25c26d8517e6e83
  server:
    port: 8080
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

