
spring:
  main:
    allow-circular-references: true
  application:
    name: listit
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/listit
    username: listit
    password: qwe123
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 704860870912-vb898r09koc1a10mvs9bbsic0cs3soac.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
  server:
    port: 8080
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
    
jwt:
  secret: bXktMzItY2hhcmFjdGVyLXVsdHJhLXNlY3VyZS1hbmQtdWx0cmEtbG9uZy1zZWNyZXQ=
  validate: 1800



