
spring:
  application:
    name: listit
  server:
    port: 8080
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html
  api-docs:
    path: /api-docs